name: Deploy bcpdaily

env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-bcpdaily
  CONTEXT_DIR: './sites/bcpdaily'
  DOCKERFILE: Dockerfile
  CAPROVER_APP: bcpdaily

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'sites/bcpdaily/**'
      - '.github/workflows/deploy-bcpdaily.yml'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v1
      - uses: oven-sh/setup-bun@v2
      - name: Build one-file binary
        run: |
          cd ${{ env.CONTEXT_DIR }}
          bun build --compile --target=bun-linux-x64 server.ts --outfile bcpdaily-server
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
      - name: Build and push Docker image with built package
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.CONTEXT_DIR }}
          file: ${{ env.CONTEXT_DIR }}/${{ env.DOCKERFILE }}
          push: true
          build-args: |
            CAPROVER_GIT_COMMIT_SHA=${{ github.sha }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Deploy to CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: ${{ secrets.CAPROVER_HOST }}
          app: ${{ env.CAPROVER_APP }}
          token: '${{ secrets.BCPDAILY_CAPROVER_APP_TOKEN }}'
          image: '${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_METADATA_OUTPUT_VERSION }}'
